Repository sonata-project/SonataClassificationBundle, pull requests merged in 2019-11, with the labels that each got.

#474 Fix calling wrong manager
  src/Block/Service/AbstractCollectionsBlockService.php
Labels: patch

#479 Dropping support for symfony < 3.4
  composer.json
  docs/reference/installation.rst
  src/Controller/CategoryAdminController.php
  src/Form/Type/CategorySelectorType.php
  tests/Controller/CategoryAdminControllerTest.php
  tests/Form/ChoiceList/CategoryChoiceLoaderTest.php
  tests/Form/Type/CategorySelectorTypeTest.php
Labels: minor

#482 Leverage `$this` binding at class scoped closures
  src/Form/Type/CategorySelectorType.php
Labels: pedantic
