Repository sonata-project/SonataClassificationBundle, pull requests merged in 2020-09, with the labels that each got.

#567 Fix loading CategoryFilter items
  src/Admin/Filter/CategoryFilter.php
  src/Model/CategoryManagerInterface.php
  tests/Admin/Filter/CategoryFilterTest.php
Labels: patch

#581 fix tests
  tests/Admin/Filter/CategoryFilterTest.php
  tests/Fixtures/Category.php
  tests/Fixtures/Context.php
Labels: pedantic

#583 Fix upgrade note
  UPGRADE-3.x.md
Labels: pedantic

#585 Add conflict with doctrine/mongodb-odm <2.0
  composer.json
Labels: minor
