Repository sonata-project/SonataClassificationBundle, pull requests merged in 2021-11, with the labels that each got.

#760 Deprecate non used methods
  src/Entity/CategoryManager.php
  src/Model/CategoryManagerInterface.php
Labels: minor

#763 Cleanup composer
  composer.json
Labels: major

#761 Fix non initialized property
  src/Model/Category.php
Labels: major

#765 Deprecate disableChildrenLazyLoading
  src/Entity/BaseCategory.php
  src/Entity/CategoryManager.php
Labels: minor

#759 Bump static analysis
  composer.json
  phpstan-baseline.neon
  phpstan.neon.dist
  psalm.xml
  src/Admin/ContextAwareAdmin.php
  src/Admin/Filter/CategoryFilter.php
  src/Admin/Filter/CollectionFilter.php
  src/Admin/TagAdmin.php
  src/Block/Service/AbstractCategoriesBlockService.php
  src/Block/Service/AbstractClassificationBlockService.php
  src/Block/Service/AbstractCollectionsBlockService.php
  src/Block/Service/AbstractTagsBlockService.php
  src/Command/FixContextCommand.php
  src/Controller/CategoryAdminController.php
  src/DependencyInjection/Configuration.php
  src/Document/CategoryManager.php
  src/Document/CollectionManager.php
  src/Document/TagManager.php
  src/Entity/BaseCategory.php
  src/Entity/CategoryManager.php
  src/Form/ChoiceList/CategoryChoiceLoader.php
  src/Form/Type/CategorySelectorType.php
  src/Model/Category.php
  src/Model/CategoryInterface.php
  src/Model/CategoryManagerInterface.php
  src/Model/Collection.php
  src/Model/CollectionInterface.php
  src/Model/Context.php
  src/Model/Tag.php
  src/Model/TagInterface.php
  tests/Admin/Filter/CategoryFilterTest.php
  tests/Admin/Filter/CollectionFilterTest.php
  tests/App/Entity/Category.php
  tests/App/Entity/Collection.php
  tests/App/Entity/Tag.php
  tests/Controller/CategoryAdminControllerTest.php
  tests/Entity/CategoryManagerTest.php
  tests/Entity/CategoryTest.php
  tests/Entity/CollectionManagerTest.php
  tests/Entity/TagManagerTest.php
  tests/Model/CategoryTest.php
  tests/Model/CollectionTest.php
  tests/Model/ContextTest.php
  tests/Model/TagTest.php
Labels: pedantic

#770 Fix phpstan build
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SonataClassificationExtension.php
  src/Model/Category.php
  src/Model/Collection.php
  src/Model/Context.php
  src/Model/Tag.php
  tests/App/Entity/Context.php
Labels: pedantic

#778 Add Symfony 6 support
  .github/workflows/test.yaml
  composer.json
  src/Controller/CategoryAdminController.php
Labels: minor
