Repository sonata-project/SonataClassificationBundle, pull requests merged in 2021-09, with the labels that each got.

#717 Manual merge
  .php-cs-fixer.dist.php
  tests/Admin/AdminTest.php
  tests/Admin/Filter/CategoryFilterTest.php
  tests/Admin/Filter/CollectionFilterTest.php
  tests/App/AppKernel.php
  tests/Block/Service/AbstractCategoriesBlockServiceTest.php
  tests/Block/Service/AbstractCollectionsBlockServiceTest.php
  tests/Block/Service/AbstractTagsBlockServiceTest.php
  tests/Controller/Api/CategoryControllerTest.php
  tests/Controller/Api/CollectionControllerTest.php
  tests/Controller/Api/ContextControllerTest.php
  tests/Controller/Api/TagControllerTest.php
  tests/Controller/CategoryAdminControllerTest.php
  tests/Entity/CategoryManagerTest.php
  tests/Form/ChoiceList/CategoryChoiceLoaderTest.php
  tests/Form/Type/CategorySelectorTypeTest.php
  tests/Functional/RoutingTest.php
  tests/Model/CategoryTest.php
  tests/Model/CollectionTest.php
  tests/Model/ContextTest.php
  tests/Model/TagTest.php
  tests/Resources/XliffTest.php
Labels: pedantic

#720 Bump PHPStan level to 1
  phpstan.neon.dist
Labels: pedantic

#719 Fix some docblocks under `Sonata\ClassificationBundle\Model\` namespace
  src/Model/Category.php
  src/Model/CategoryInterface.php
  src/Model/Collection.php
  src/Model/CollectionInterface.php
  src/Model/Context.php
  src/Model/ContextInterface.php
  src/Model/Tag.php
  src/Model/TagInterface.php
Labels: patch

#722 Add missing deps
  composer.json
Labels: minor

#724 Fix ODM queries
  src/Document/CategoryManager.php
  src/Document/CollectionManager.php
  src/Document/TagManager.php
Labels: patch

#721 Bump PHPStan level to 2
  UPGRADE-3.x.md
  phpstan-baseline.neon
  phpstan.neon.dist
  src/Admin/Filter/CategoryFilter.php
  src/Admin/Filter/CollectionFilter.php
  src/Block/Service/AbstractCategoriesBlockService.php
  src/Entity/CategoryManager.php
  src/Model/CategoryInterface.php
  src/Model/CollectionInterface.php
  src/Model/TagInterface.php
  src/Serializer/ContextSerializerHandler.php
  tests/Block/Service/AbstractCategoriesBlockServiceTest.php
  tests/Block/Service/AbstractCollectionsBlockServiceTest.php
  tests/Block/Service/AbstractTagsBlockServiceTest.php
  tests/Controller/CategoryAdminControllerTest.php
Labels: minor

#726 Bump PHPStan level to 3
  phpstan.neon.dist
  src/Block/Service/AbstractCategoriesBlockService.php
  src/Block/Service/AbstractClassificationBlockService.php
  src/Controller/Api/CategoryController.php
  src/Controller/Api/CollectionController.php
  src/Controller/Api/ContextController.php
  src/Controller/Api/Legacy/CategoryController.php
  src/Controller/Api/Legacy/CollectionController.php
  src/Controller/Api/Legacy/ContextController.php
  src/Controller/Api/Legacy/TagController.php
  src/Controller/Api/TagController.php
  src/Form/Type/CategorySelectorType.php
  tests/Admin/Filter/QueryBuilder.php
  tests/App/Entity/Context.php
  tests/Controller/CategoryAdminControllerTest.php
  tests/Form/Type/CategorySelectorTypeTest.php
Labels: minor

#727 Bump PHPStan level to 4
  phpstan.neon.dist
  src/Controller/Api/CategoryController.php
  src/Form/Type/CategorySelectorType.php
Labels: minor

#736 Update homepage
  composer.json
Labels: pedantic
