Repository sonata-project/SonataClassificationBundle, pull requests merged in 2022-02, with the labels that each got.

#818 Remove sandbox mention
  docs/reference/classification_types.rst
Labels: docs

#821 Fix edit group translation
  src/Admin/CategoryAdmin.php
  src/Resources/translations/SonataClassificationBundle.de.xliff
  src/Resources/translations/SonataClassificationBundle.en.xliff
  src/Resources/translations/SonataClassificationBundle.fr.xliff
  src/Resources/translations/SonataClassificationBundle.hu.xliff
  src/Resources/translations/SonataClassificationBundle.it.xliff
  src/Resources/translations/SonataClassificationBundle.nl.xliff
Labels: patch

#820 Backport changes from AdminBundle to CategoryAdminController
  src/Controller/CategoryAdminController.php
  tests/App/Action/CategoryAdminTest.php
Labels: bug, patch

#830 Solve adminbundle deprecations
  composer.json
  src/Admin/ContextAwareAdmin.php
  src/Resources/config/admin.php
  tests/Admin/AdminTest.php
  tests/Block/Service/AbstractCategoriesBlockServiceTest.php
  tests/Block/Service/AbstractCollectionsBlockServiceTest.php
  tests/Block/Service/AbstractTagsBlockServiceTest.php
Labels: patch
