Repository sonata-project/SonataClassificationBundle, pull requests merged in 2023-07, with the labels that each got.

#937 DevKit updates for 4.x branch
  .github/workflows/test.yaml
Labels: automerge, dev-kit

#938 DevKit updates for 5.x branch
  .github/workflows/test.yaml
Labels: automerge, dev-kit

#940 Solve static analysis
  src/Block/Service/AbstractCategoriesBlockService.php
  src/Block/Service/AbstractCollectionsBlockService.php
  src/Block/Service/AbstractTagsBlockService.php
  tests/App/AppKernel.php
Labels: pedantic

#939 Fix translations
  src/Resources/translations/SonataClassificationBundle.en.xliff
  src/Resources/translations/SonataClassificationBundle.it.xliff
Labels: patch
