Repository sonata-project/SonataClassificationBundle, pull requests merged in 2023-04, with the labels that each got.

#907 Test create initial category
  src/Document/CategoryManager.php
  src/Entity/CategoryManager.php
  tests/Functional/Admin/CategoryAdminTest.php
Labels: patch

#909 Fix MongoDB Mapping
  src/Resources/config/doctrine/BaseCategory.mongodb.xml
  src/Resources/config/doctrine/BaseContext.mongodb.xml
  src/Resources/config/doctrine/BaseTag.mongodb.xml
Labels: pedantic

#911 Fix orm mapping
  src/Resources/config/doctrine/BaseCategory.orm.xml
  src/Resources/config/doctrine/BaseCollection.orm.xml
  src/Resources/config/doctrine/BaseContext.orm.xml
  src/Resources/config/doctrine/BaseTag.orm.xml
Labels: patch

#914 Drop Symfony 4.4 and Twig 2
  .github/workflows/test.yaml
  composer.json
  src/Command/FixContextCommand.php
  src/Resources/config/admin.php
  src/Resources/config/command.php
  src/Resources/config/controllers.php
  src/Resources/config/form.php
  src/Resources/config/orm.php
  tests/App/AppKernel.php
  tests/App/config/config.yaml
  tests/App/config/config_symfony_v4.yaml
  tests/App/config/config_symfony_v5.yaml
  tests/App/config/config_symfony_v6.yaml
  tests/Entity/CategoryManagerTest.php
  tests/Entity/CollectionManagerTest.php
  tests/Entity/TagManagerTest.php
  tests/Functional/Admin/CategoryAdminTest.php
  tests/Functional/Admin/CollectionAdminTest.php
  tests/Functional/Admin/ContextAdminTest.php
  tests/Functional/Admin/TagAdminTest.php
Labels: minor

#916 DevKit updates for 4.x branch
  .github/workflows/auto-merge-dev-kit.yaml
Labels: automerge

#917 DevKit updates for 5.x branch
  .github/workflows/auto-merge-dev-kit.yaml
Labels: automerge

#918 DevKit updates for 4.x branch
  README.md
Labels: automerge

#919 Fix CHANGELOG
  CHANGELOG.md
Labels: pedantic
