Repository sonata-project/SonataClassificationBundle, pull requests merged in 2023-06, with the labels that each got.

#932 Release 4.7.0
  CHANGELOG.md
Labels: dev-kit

#933 DevKit updates for 4.x branch
  .github/FUNDING.yml
Labels: automerge, dev-kit

#934 DevKit updates for 5.x branch
  .github/FUNDING.yml
Labels: automerge, dev-kit

#935 Cleanup older upgrade files
  UPGRADE-3.x.md
  UPGRADE-4.x.md
Labels: pedantic

#936 Update rector
  composer.json
Labels: pedantic
