Repository sonata-project/SonataClassificationBundle, pull requests merged in 2023-05, with the labels that each got.

#922 DevKit updates for 4.x branch
  .github/workflows/documentation.yaml
  .readthedocs.yaml
  docs/conf.py
  docs/reference/advanced_configuration.rst
  docs/requirements.txt
Labels: automerge, dev-kit

#924 Up rector to 0.16
  composer.json
Labels: pedantic

#925 DevKit updates for 4.x branch
  .github/workflows/test.yaml
Labels: automerge, dev-kit

#927 Add support for form-extensions 2.0
  composer.json
Labels: minor

#928 Release 4.6.0
  CHANGELOG.md
Labels: dev-kit
