Repository sonata-project/SonataClassificationBundle, pull requests merged in 2024-06, with the labels that each got.

#966 Bump rector
  composer.json
Labels: pedantic

#967 DevKit updates for 4.x branch
  .github/workflows/documentation.yaml
  .github/workflows/lint.yaml
  .github/workflows/qa.yaml
  .github/workflows/symfony-lint.yaml
  .github/workflows/test.yaml
  psalm.xml
Labels: automerge, dev-kit

#968 Solve internal class usage
  src/DependencyInjection/SonataClassificationExtension.php
Labels: patch
